export const EVENTS = {
  START_DIALOGUE: "START_DIALOGUE",
  END_DIALOGUE: "END_DIALOGUE",
  OPEN_PUZZLE: "OPEN_PUZZLE",
  PUZZLE_COMPLETE: "PUZZLE_COMPLETE",
  ALGORITHM_UNLOCKED: "ALGORITHM_UNLOCKED",
  SHOW_PROMPT: "SHOW_PROMPT",
  HIDE_PROMPT: "HIDE_PROMPT",
};
